### ISSUE TITLE
Host site with HTTPS

### ISSUE THREAD

**Issue by parberge** [codelabsab/timereport-ui#15]
To increase security the site `timereport.codelabs.se` should be served via HTTPS.

Actions:
* Enable cloudfront
* Enable HTTPS: (https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-https-requests-s3/)

**Comment by mattiaslundberg** [comment]
`dev.timereport.codelabs.se` and `timereport.codelabs.se` are now served over HTTPS!
