### ISSUE TITLE
Export summary as excel file

### ISSUE THREAD

**Issue by kamigerami** [codelabsab/timereport-ui#57]
We currently have to add all the timereport discrepancies in an excel spreadsheet and provide it to the firm that does our bookkeeping for salaries and such.

It would be nice to be able to just export the data directly from the timereport UI as excel spreadsheet.

**Comment by parberge** [comment]
An example spreadsheet would be useful to provide.

Also does it need to be an actual excel file or is a CSV file sufficient?

**Comment by kamigerami** [comment]
<img width="1122" alt="Skärmavbild 2021-09-12 kl  13 37 39" src="https://user-images.githubusercontent.com/9321510/132986062-96d3ef61-50d3-4724-ba7f-c7f784f6f636.png">

"namn", "typ", "datum från", "datum till", "antal" is sufficient.

**Comment by kamigerami** [comment]
Initial WIP PR 

<img width="1235" alt="Skärmavbild 2021-09-12 kl  18 17 22" src="https://user-images.githubusercontent.com/9321510/132995097-900300ac-f813-4051-b759-f0b85cd708ed.png">
